name: USBIP Client
version: 1.0.0
slug: usbip_client
description: Connects to remote USBIP servers and attaches USB devices.
url: "https://github.com/rede-analista/ha-add-on-USBIP"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
boot: auto
options:
  devices: []
schema:
  devices:
    type: list
    name: Device
    description: List of devices to connect to.
    required: true
    schema:
      name:
        type: string
        name: Name
        description: Name of the device.
        required: true
      host:
        type: string
        name: Host
        description: IP address of the remote USBIP server.
        required: true
      bus_id:
        type: string
        name: Bus ID
        description: Bus ID of the USB device.
        required: true
udev: true
usb: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
