name: "USBIP Client"
version: "1.0"
slug: "usbip_client"
description: "Add-on to connect to remote USBIP servers"
url: "https://github.com/rede-analista/ha-add-on-USBIP"
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
init: false
uart: true
udev: true
usb: true
hassio_api: true
hassio_role: manager
homeassistant_api: true  
startup: "services"
boot: "auto"
options:
  devices:
    - name: "Device1"
      host: "192.168.1.100"
      bus_id: "1-1"
    - name: "Device2"
      host: "192.168.1.101"
      bus_id: "1-2"
schema:
  devices:
    - name: str
      host: str
      bus_id: str
